type GameInfo = {
    totalPokemons: number;
    totalSprites: number;
    spritesWithCustomSprites: number;
    totalCustomSprites: number;
    totalArtists: number;
    autoGeneratedSprites: number;
  };
  
  const gameInfo: GameInfo = {
    totalPokemons: 470,                // Total number of base Pokémon (if different from fusions)
    totalSprites: 221390,              // Total number of Pokémon fusions
    spritesWithCustomSprites: 123094,  // Pokémon fusions with custom sprites
    totalCustomSprites: 172095,        // Total number of custom sprites
    totalArtists: 6736,                // Total number of contributing artists
    autoGeneratedSprites: 220000       // Approximate number of auto-generated sprites
  };
  
  export {
    gameInfo
  };
  